name: 🚀 Feature
description: A request, idea, or new functionality
title: "[feature]: "
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this enhancement hasn't already been submitted by someone else by looking through other open/closed issues.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the enhancement.
