name: "📋 Task"
description: "A task with a clear end-user, intent and purpose."
title: "[task]: "
type: Task

body:
  - type: markdown
    attributes:
      value: |
        Please ensure this task isn't already requested by searching existing issues.

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Use the standard agile story format.
      value: |
        **As a** [role],
        **I want** [an action or feature],
        **So that** [a reason or benefit].
    validations:
      required: true

  - type: input
    id: time_estimate
    attributes:
      label: Time Estimate
      description: Rough estimate of how much time this task will take to complete in actual hours spent.
      placeholder: "e.g. 4 hours, 8 hours, 32 hours"

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What must be true for the task to be considered complete.
      placeholder: |
        Examples:
        - [ ] When the pipeline runs, the new caching is used and reduces build time.
        - [ ] When the feature flag is enabled, the new UI is visible to all users.
        - [ ] When a user can press the green button without getting an error.

  - type: textarea
    id: ideas
    attributes:
      label: Ideas and considerations
      description: Provide any design ideas, solution directions, or considerations for implementation.
      placeholder: |
        - Consider using library X for better performance.
        - Make sure to follow accessibility guidelines.

  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Note any prerequisites like required data, accesses, or environment setup.
      placeholder: |
        - [ ] Administrative rights to an AWS Account
        - [ ] Data on PRs merged in march.
        - [ ] A tenant on the Developer Cloud Platform.

  - type: checkboxes
    id: continuous_prioritization_criteria
    attributes:
      label: Continuous Prioritization Criteria
      description: All criteria must be marked with "✅" before the task is sufficiently described for prioritization to be made.
      options:
        - label: "'Purpose' is clear and understood"
        - label: "'Relationships' is configured to link Objective, Epic, LeanIX application, blocked by or is-blocking"

  - type: checkboxes
    id: refinement_criteria
    attributes:
      label: Refinement Criteria
      description: All criteria must be marked with "✅" before the task is refined sufficiently for development to begin.
      options:
        - label: "'Ideas and considerations' are relevant and helpful"
        - label: "'Acceptance Criteria' are obtainable and testable"
        - label: "'Prerequisites' are relevant beyond common knowledge"
        - label: "'Time Estimate' is provided"
        - label: "'Sub-issues' are created to break down the work if needed"
        - label: "'Known unknowns' are identified, so the task can flow uninterrupted"
