name: "📋 Task"
description: "A general task with a clear purpose."
title: "[task]: "
type: Task

body:
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: Briefly explain why this task is important and what it delivers, by focusing on the "What" and "Why".
      placeholder: |
        To reduce build time in CI, we need to add caching to CI pipelines.
    validations:
      required: true

  - type: input
    id: time_estimate
    attributes:
      label: Time Estimate
      description: Rough estimate of how much time this task will take to complete in actual hours spent.
      placeholder: "e.g. 4 hours, 8 hours, 32 hours"

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What must be true for the task to be considered complete.
      placeholder: |
        Examples:
        - [ ] When the pipeline runs, the new caching is used and reduces build time.
        - [ ] When the feature flag is enabled, the new UI is visible to all users.
        - [ ] When a user can press the green button without getting an error.

  - type: textarea
    id: ideas
    attributes:
      label: Ideas and considerations
      description: Provide any design ideas, solution directions, or considerations for implementation.
      placeholder: |
        - Consider using library X for better performance.
        - Make sure to follow accessibility guidelines.

  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Note any prerequisites like required data, accesses, or environment setup.
      placeholder: |
        - [ ] Administrative rights to an AWS Account
        - [ ] Data on PRs merged in march.
        - [ ] A tenant on the Developer Cloud Platform.

  - type: checkboxes
    id: refinement_criteria
    attributes:
      label: Refinement Criteria
      description: All criteria must be marked with "✅" before the task is refined sufficiently for development to begin.
      options:
        - label: "'Purpose' is clear and understood"
        - label: "'Ideas and considerations' are relevant and helpful"
        - label: "'Acceptance Criteria' are obtainable and testable"
        - label: "'Prerequisites' are relevant beyond common knowledge"
        - label: "'Time Estimate' is provided"
        - label: "'Relationships' is configured to link objective, blocked by or is-blocking"
        - label: "'Sub-issues' are created to break down the work if needed"
        - label: "'Known unknowns' are identified, so the task can flow uninterrupted"
