name: "Task"
description: "A general task with a clear purpose."
title: "[Task] <short title>"
type: Task

body:
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: Briefly explain why this task is important and what it delivers.
      placeholder: |
        To reduce build time in CI, we need to add caching to CI pipelines.
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options: [S, M, L]

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What must be true for the task to be considered complete.
      placeholder: |
        Examples:
        - [ ] When the pipeline runs, the new caching is used and reduces build time.
        - [ ] When the feature flag is enabled, the new UI is visible to all users.
        - [ ] When a user can press the green button without getting an error.
  - type: textarea
    id: design
    attributes:
      label: Design / Solution Direction
      description: Short note or link to diagram/ADR if relevant.

  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Note any prerequisites like required data, accesses, or environment setup.
      placeholder: |
        - [ ] Administrative rights to an AWS Account
        - [ ] Data on PRs merged in march.
        - [ ] A tenant on the Developer Cloud Platform.

  - type: checkboxes
    id: refinement_ready
    attributes:
      label: Refinement Ready (Definition of Ready)
      description: All must be ✅ before the task can move to Active Development.
      options:
        - label: Purpose is clear and understood
        - label: Acceptance Criteria are defined
        - label: Dependencies are identified and linked
        - label: Design / solution direction is agreed
        - label: Data & environments are in place
        - label: Size is estimated and acceptable
        - label: No unknown unknowns
